[versions]
java = "21"

spring-framework = "3.3.3"
spring-dependency-managment = "1.1.6"
gradle-node = "7.1.0"
node = "22.13.1"
npm = "11.1.0"

jolt = "0.1.8"

# service APIs deps
common-api = "0.0.2"
localization-api = "0.0.7"
error-api = "0.0.16"
web-app-api = "0.0.6"

[libraries]
jolt = { module = "com.bazaarvoice.jolt:jolt-core", version.ref = "jolt"}

common-api = { module = "com.github.sibdevtools:api-common", version.ref = "common-api" }
localization-api = { module = "com.github.sibdevtools:api-localization", version.ref = "localization-api" }
error-api = { module = "com.github.sibdevtools:api-error", version.ref = "error-api" }
web-app-api = { module = "com.github.sibdevtools:api-web-app", version.ref = "web-app-api" }

[bundles]
service-api = [
    "common-api",
    "localization-api",
    "error-api",
    "web-app-api"
]

[plugins]
spring-framework-boot = { id = "org.springframework.boot", version.ref = "spring-framework" }
spring-dependency-managment = { id = "io.spring.dependency-management", version.ref = "spring-dependency-managment" }

node = { id = "com.github.node-gradle.node", version.ref = "gradle-node" }